---
- name: add city_daoxila_com nginx conf
  template:
    src: nginx.city_daoxila_com.conf.j2
    dest: /etc/nginx/sites-enabled/city_daoxila_com.conf
  notify: reload nginx
- name: start nginx
  service:
    name: tengine
    state: started
    enabled: yes
