---
# 部署daoxila_v3
- hosts:
  - daoxila_v3
  tasks:
  - service: name=httpd state=stopped
  - yum: name=daoxila_v3 state=latest update_cache=yes
  - file: path=/www/daoxila/daoxila_v3 owner=nobody group=nobody state=directory recurse=yes
  - yum: name=daoxila_lib state=latest update_cache=yes
  - file: path=/www/daoxila/daoxila_lib owner=nobody group=nobody state=directory recurse=yes
  - file: path=/www/daoxila/library state=link src=daoxila_lib
  - service: name=httpd state=started
  serial: "30%"
