---
# solr负载均衡反向代理
- name: add solr nginx conf
  template:
    src: solr.site.conf.j2
    dest: /etc/nginx/sites-enabled/solr.conf
  notify: restart nginx
- name: start nginx
  service:
    name: tengine
    state: started
    enabled: yes
