---
- template:
    src: daoxila_discuz.conf.j2
    dest: /etc/httpd/conf.d/daoxila_discuz.conf
  notify: restart apache
- name: start apache
  service:
    name: httpd
    enabled: yes
    state: started
