---
# 安装tengine
- name: install tengine
  yum:
    name: daoxila-tengine
    state: present
- name: clean default site conf
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/nginx/conf.d/example_ssl.conf
    - /etc/nginx/conf.d/default.conf
- name: default server
  copy:
    src: default.conf
    dest: /etc/nginx/sites-enabled/default.conf
- name: conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
- name: upstream folder
  file:
    path: /etc/nginx/upstreams
    state: directory
- name: modules conf folder
  file:
    path: /etc/nginx/modules-enabled
    state: directory
- name: load rewrite module
  copy:
    src: ngx_http_rewrite_module.conf
    dest: /etc/nginx/modules-enabled/ngx_http_rewrite_module.conf
