---
# 安装php taint 扩展
- name: install gcc
  yum:
    name: gcc
    state: present
- lineinfile:
    line: "#define ZVAL_COPY_VALUE(z, v) do { (z)->value = (v)->value; Z_TYPE_P(z) = Z_TYPE_P(v); } while (0)"
    dest: /usr/include/php/Zend/zend.h
    state: present
- lineinfile:
    line: "#define INIT_PZVAL_COPY(z, v) do { ZVAL_COPY_VALUE(z, v); Z_SET_REFCOUNT_P(z, 1); Z_UNSET_ISREF_P(z); } while (0)"
    dest: /usr/include/php/Zend/zend.h
    state: present
- name: install taint
  shell: "pecl install taint"
  args:
    creates: /usr/lib64/php/modules/taint.so
- name: load taint
  copy:
    dest: /etc/php.d/taint.ini
    content: extension=taint.so
