---
# 增加一个admin用户
- name: create user for remote login
  user:
    name: "{{ admin_username }}"
    comment: user for remote login
    password: "{{ admin_password|password_hash('sha512') }}"
    update_password: always
    state: present
    createhome: yes
    shell: /bin/bash
- name: create .ssh/
  file:
    path: /home/{{ admin_username }}/.ssh
    state: directory
    mode: 0700
    owner: "{{ admin_username }}"
    group: "{{ admin_username }}"
- name: authorized_keys file
  copy:
    src: authorized_keys
    dest: /home/{{ admin_username }}/.ssh/authorized_keys
    mode: 0600
    owner: "{{ admin_username }}"
    group: "{{ admin_username }}"
- name: add user to sudoers
  lineinfile:
    dest: /etc/sudoers
    line: "{{ admin_username }} ALL=(ALL) NOPASSWD: ALL"
    regexp: "^{{ admin_username }}"
