---
- file:
    path: "{{ project_root }}/{{ project }}/pm2start.sh"
    mode: u+x
- command: "{{ project_root }}/{{ project }}/pm2start.sh"
  args:
    chdir: "{{ project_root }}/{{ project }}"
- command: "pm2 save"
